# docker-compose.yml
# version: '3.8'

services:
  app:
    build: .
    image: egargale/gexdata:latest
    env_file:
      - .env_docker
    ports:
      - "9999:8000"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  backend:
    driver: bridge
