# docker-compose.yml
# version: '3.8'

services:
  app:
    build: .
    # image: egargale/gexdata:latest
    develop:
      watch:
      # Sync the working directory with the `/app` directory in the container
      - action: sync
        path: .
        target: /app
        # Exclude the project virtual environment
        ignore:
          - .venv/
          
      # Rebuild the image on changes to the `pyproject.toml`
      - action: rebuild
        path: ./pyproject.toml
    env_file:
      - .env_docker
    ports:
      - "9999:80"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3
  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    ports:
      - "4200:4200"
    command: ["prefect", "server", "start", "--host", "0.0.0.0"]
    networks:
      - backend
    restart: unless-stopped    

networks:
  backend:
    driver: bridge
